version: '3'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '6379:6379'

  uploader-service:
    build:
      context: ./uploader
    env_file:
      - ./uploader/.env
    ports:
      - '1337:1337'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  deployer-service:
    build:
      context: ./deployer
    env_file:
      - ./deployer/.env
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  server-service:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - '8080:8080'
    depends_on:
      - redis

  client-service:
    build:
      context: ./client-app
    env_file:
      - ./client-app/.env
    ports:
      - '3000:3000'
    depends_on:
      - server-service
    environment:
      - VITE_API_ENDPOINT=uploader-service
      - VITE_DEPLR_SERVER=server-service
